default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tra-gori
  password: password
  host: localhost

development:
  <<: *default
  database: tra_gori_development

test:
  <<: *default
  database: tra_gori_test

production:
  <<: *default
  password: <%= ENV["TRA_GORI_DATABASE_PASSWORD"] %>
